# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.CharField(max_length=50, verbose_name='Ссылка')),
                ('description', models.TextField(max_length=300, verbose_name='Текст')),
                ('logo', models.ImageField(upload_to='media/client_logo', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Наши клиенты',
            },
        ),
    ]
