# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории пестециды',
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название товара')),
                ('text', models.TextField(max_length=2000, verbose_name='Описание')),
                ('sort', models.CharField(blank=True, max_length=300, verbose_name='Сорт')),
                ('image', models.FileField(blank=True, upload_to='media/pest/price', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, upload_to='media/pest/price', verbose_name='Прайс лист')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Пестециды',
            },
        ),
    ]
