# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(max_length=1200, verbose_name='Контент'),
        ),
    ]
